const Routes = {
    LOADING: "LOADING",
    LOGIN_STACK: "LOGIN_STACK",
    LOGIN_SCREEN: "LOGIN_SCREEN",
    MAIN_APP: "MAIN_APP", //STACK
    APP_INTRO: "APP_INTRO",
    HOME_STACK: "HOME_STACK", // HOMESTACK CONTAINER FOR TABS
    HOME_TABS: "HOME_TABS", //HOME TABS
    HOME_SCREEN: "HOME",
    CHATS_STACK: "CHAT_STACK",
    CHATS_SCREEN: "CHATS",
    CHAT_ROOM_SCREEN: "CHATROOM",
};

export default Routes;
